config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  resources :categories
  resources :accounts, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'accounts#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as:'logout'
  resources :stories

end

app/models/post.rb
class Post < ApplicationRecord
  paginates_per 5
  belongs_to :user, optional: true
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :comments, :foreign_key => "post_id"
  has_rich_text :body
  extend FriendlyId
  friendly_id :title, use: :slugged
  # def sum(num, other_num)
  #   num + other_num
  # end

  def self.published
    where(state: "publish")
  end

  def self.popular
    self.published.order(view_count: :desc).limit(3)
  end

  def self.recent
    self.published.order(updated_at: :desc).limit(3)
  end

  def publish?
    self.state == "publish"
  end

  def draft?
    self.state == "draft"
  end

  def self.search(search)
    if search
      Post.published.where("title LIKE ?", "%#{search}%")
    else
      Post.published
    end
  end

  def related
    category_ids = self.category_ids
    post_category_ids = PostCategory.where(category_id: category_ids).pluck(:post_id)
    Post.where(id: post_category_ids).where(state: 'publish').limit(3)
  end

  def previous
    Post.published.where('id < ?', self.id).order(id: :asc).last
  end

  def next
    Post.published.where('id > ?', self.id).order(id: :asc).first
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_popular_posts, except: [:create, :destroy]
  before_action :load_categories, except: [:create, :destroy]
  before_action :require_login, except: [:show]
  before_action :load_recent_posts, except: [:create, :destroy]
  before_action :load_recent_comments, except: [:create, :destroy]


  def new
    @post = Post.new
    @categories = Category.all
  end

  def create
    flash[:notice] = "Post has been created"
    # title = params[:post][:title]
    # body = params[:post][:body]
    # post = Post.new(title: title, body: body)
    # post.save

    # BESOK YANG RELASINYA PAKAI OBJEK
    post = Post.new(resource_params)
    category_ids = params[:post][:categories]
    post.category_ids = category_ids
    post.save

    redirect_to posts_path
  end

  def edit
    @post = Post.friendly.find(params[:id])
    @categories = Category.all
    @category_ids = @post.category_ids
  end

  #when we run edit method then we update the database by update method
  def update
    # render plain: params.inspect #to inspect what kind of params that be return value of this method
    flash[:notice] = "Post has been updated"
    post = Post.friendly.find(params[:id]) #catch the post which has the active id
    post.attributes = resource_params #update the post with attributes not update method in order to saving the update in the end, bzos we have a unsaved categories
    category_ids = params[:post][:categories] #catch the categories of the current post
    post.category_ids = category_ids #assign the new category_ids with the updated category
    post.save # ya save lah
    redirect_to posts_path #redirect ke post yg bersangkutan
  end

  def destroy
    flash[:notice] = "Post has been deleted"
    @post = Post.friendly.find(params[:id]) #catch the post which has the active id
    @post.destroy
    redirect_to posts_path
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.friendly.find(params[:id])
    @related_posts = @post.related
    @previous_post = @post.previous
    @next_post = @post.next

    if @post.draft?
      redirect_to root_path
    end
  end

  private

  def resource_params
    params.require(:post).permit(:title, :body, :state)
  end


end

app/views/posts/edit.html.erb
<%= form_for(@post) do |f| %>
  <%= f.label :title %></br>
  <%= f.text_field :title %></br>

  <%= f.label :body %></br>
  <%= f.rich_text_area :body %></br>

  <%= f.label :categories %></br>
  <% @categories.each do |category| %>
    <%= f.check_box :categories, { multiple: true, checked: @category_ids.include?(category.id) }, category.id, false %> <%= category.name %> </br>
  <% end %>

  <%= f.label :state %></br>
  <%= f.select :state, ['draft', 'publish']%> </br>
  
  <%= f.submit "Save" %></br>
<%end%>

app/views/posts/index.html.erb
<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %>
</br>

<table>
  <tr>
    <td> Title </td>
    <td> Body </td>
    <td> Category </td>
    <td> State </td>
    <td> Action </td>
  </tr>

  <% @posts.each do |post| %>

  <tr>
    <td><%= post.title %></td>
    <td><%= truncate(strip_tags(post.body.to_s), length: 160) %></td>
    <% array = [] %>
    <% post.categories.each do |category| %>
      <% array << category.name %>
    <% end %>
    <td><%= array.join(', ') %></td>
    <td><%= post.state %></td>
    <td><%= link_to 'Detail', post_path(post) %> |
        <%= link_to 'Edit', edit_post_path(post) %> |
        <%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: "Are you sure?"} %> </td>
  </tr>
  <%end%>

  <tr>
    <td><%= link_to 'New Post', new_post_path %></td>
  </tr>
</table>

app/views/posts/new.html.erb
<%= form_for(@post) do |f| %>
  <%= f.label :title %></br>
  <%= f.text_field :title %></br>

  <%= f.label :body %></br>
  <%= f.rich_text_area :body %></br>

  <%= f.label :categories %></br>
  <% @categories.each do |category| %>
    <%= f.check_box :categories, { multiple: true }, category.id, false %> <%= category.name %> </br>
  <% end %>

  <%= f.label :state %></br>
  <%= f.select :state, ['draft', 'publish']%> </br>
  
  <%= f.submit "Save" %></br>
<%end%>

app/views/posts/show.html.erb
<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %>

</br>

<div class="card">
  <%= @post.created_at.strftime("%e %b %Y") %>
  |
  <% @post.categories.each do |category| %>
    <%= link_to category.name, category_path(category) %>
  <% end %>

  <h2><%= @post.title %></h2>
  <p><%= @post.body %></p>

  <h2>Share this</h2>
  <%= link_to image_tag("share_facebook.png"), "https://www.facebook.com/sharer.php?u=#{post_url(@post)}", target: :_blank %>
  <%= link_to image_tag("share_twitter.png"), "https://twitter.com/intent/tweet?url=#{post_url(@post)}", target: :_blank %>
  <%= link_to image_tag("share_linkedin.png"), "https://www.linkedin.com/sharing/share-offsite/?url=#{post_url(@post)}", target: :_blank %>

  <h2>Previous Post</h2>
  <% if @previous_post.present? %>
    <div><%= link_to @previous_post.title, post_path(@previous_post) %></div>
  <% else %>
    -
  <% end %>

  <h2>Next Post</h2>
  <% if @next_post.present? %>
    <div><%= link_to @next_post.title, post_path(@next_post) %></div>
  <% else %>
    -
  <% end %>

  <h2>You May Also Like </h2>
  <% if @related_posts.present? %>
    <% @related_posts.each do |related_post| %>
      <div><%= link_to related_post.title, post_path(related_post) %></div>
    <% end %>
  <% end %>

  <% if @post.comments.present? %>
    <h2>Comments</h2>
    <% @post.comments.each do |comment| %>
      <div id="<%= comment.id %>">
        <p>
          <strong>Commenter:</strong>
          <%= comment.name %>
        </p>
        <p>
          <strong>Comment:</strong>
          <%= comment.body %>
        </p>
      </div>
    <% end %>
  <% end %>

  <h2>Add a comment:</h2>
  <%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %><br>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

  <% if current_user %>
    <%= link_to "Edit", edit_post_path(@post) %>
    <%= link_to "Back", root_path %>
  <% end %>
</div>