config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  resources :categories
  resources :accounts, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'accounts#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as:'logout'
  resources :stories

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories
  has_many :posts, through: :post_categories
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_popular_posts, except: [:create, :destroy]
  before_action :load_categories, except: [:create, :destroy]
  before_action :load_recent_posts, except: [:create, :destroy]
  before_action :load_recent_comments, except: [:create, :destroy]
  before_action :require_login, except: [:show]

  def new
    @category = Category.new
  end

  def create
    flash[:notice] = "Category has been created"
    category = Category.new(resource_params)
    category.save
    redirect_to categories_path
  end

  def edit
    @category = Category.friendly.find(params[:id])
  end

  def update
    flash[:notice] = "Category has been updated"
    category = Category.friendly.find(params[:id])
    category.update(resource_params)
    redirect_to category_path(category)
  end

  def destroy
    category = Category.friendly.find(params[:id])
    post_category = PostCategory.find_by(category_id: category.id)
    if post_category
      flash[:notice] = "Category cannot be deleted"
    else
      category.destroy
      flash[:notice] = "Category has been deleted"
    end
    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def show
    category = Category.friendly.find(params[:id])
    id = category.id
    post_ids = PostCategory.where(category_id: id).pluck(:post_id)
    @posts = Post.where(id: post_ids).where(state: 'publish').page params[:page]

    render 'home/index'
  end

  private

  def resource_params
    params.require(:category).permit(:name)
  end

end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <%= f.label :name %></br>
  <%= f.text_field :name %></br>

  <%= f.submit "Save" %></br>
<%end%>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %>
</br>

<table>
  <tr>
    <td> Name </td>
    <td> Action </td>
  </tr>

  <% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Detail', category_path(category) %> |
        <%= link_to 'Edit', edit_category_path(category) %> |
        <%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: "Are you sure?"} %> </td>
  </tr>
  <% end %>

</tr>

<tr>
  <td><%= link_to 'New Category', new_category_path %></td>
</tr>
</table>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<% if flash[:notice].present? %>
  <%= flash[:notice] %>
<% end %>
</br>

Name Category : <%= @category.name %></br>