config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  resources :categories
  resources :accounts, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'accounts#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as:'logout'
  resources :stories

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Narauju</title>

    <meta property="og:title" content="<%= @post&.title || "Narauju Blog Post" %>" />
    <meta property="og:description" content="<%= truncate(strip_tags(@post&.body.to_s), length: 160) || "Blognya Narauju" %>" />
    <meta property="og:image" content="https://instagram.fjog3-1.fna.fbcdn.net/v/t51.2885-15/e35/p1080x1080/91625790_258447118522128_5151132685765713772_n.jpg?_nc_ht=instagram.fjog3-1.fna.fbcdn.net&_nc_cat=100&_nc_ohc=MmXlswJPIjkAX-oCWt8&oh=6b13e5c80d7e80750f72b4afe5a9c09e&oe=5EE4FC94" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <h2><%= link_to "NARAUJU BLOG", root_path %></h2>
    </div>
    <div class="card">
      <div>
        <% if current_user %>
          Logged in as <%= current_user.username %> |
          <%= link_to "Logout", logout_path %> |
          <%= link_to "Create New Post", new_post_path %>
        <% else %>
          <%= link_to "Sign Up", signup_path %> |
          <%= link_to "Login", login_path %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="leftcolumn">
        <% if flash[:notice].present? %>
          <%= flash[:notice] %>
        <% end %>

        <%= yield %>
      </div>

      <div class="rightcolumn">
        <%= form_tag root_path, method: 'get' do  %>
          <p>
            <%= text_field_tag :search %>
            <%= submit_tag "Search", name: nil %>
          </p>
        <% end %>

        <div class="card">
          <h2>About Me</h2>
          <%= image_tag("nisfa.jpg", size: "225x150") %>
          <p> Hi, nama saya Hauril Maulida Nisfari, seorang Ibu dan Istri, suka menulis dan ngoding.
              Dulu sempat bekerja sebagai Odoo Developer dan sekarang sedang belajar Ruby on Rails.</p>
        </div>

        <div class="card">
          <h3>Popular Posts</h3>
          <% if @popular_posts.present? %>
            <% @popular_posts.each do |popular_post| %>
              <div><%= link_to popular_post.title, post_path(popular_post) %></div></br>
            <% end %>
          <% else %>
            Belom ada popular post
          <% end %>
        </div>

        <div class="card">
          <h3>Recent Posts</h3>
          <% if @recent_posts.present? %>
            <% @recent_posts.each do |recent_post| %>
              <div><%= link_to recent_post.title, post_path(recent_post) %></div></br>
            <% end %>
          <% else %>
            Belom ada recent post
          <% end %>
        </div>

        <div class="card">
          <h3>Recent Comments</h3>
          <% if @recent_comments.present? %>
            <% @recent_comments.each do |recent_comment| %>
              <div><%= recent_comment.name %> on <%= link_to recent_comment.post.title, post_path(recent_comment.post, anchor: recent_comment.id) %></div></br>
            <% end %>
          <% else %>
            Belom ada recent comment
          <% end %>
        </div>

        <div class="card">
          <h3>My Repository</h3><br>
          <%= link_to image_tag("github.png"), "https://github.com/haurilnisfari"  %>
        </div>
        <div class="card">
          <h3>Category</h3>
          <% @categories.each do |category| %>
            <div><%= link_to category.name, category_path(category) %></div></br>
          <% end %>
        </div>
      </div>
    </div>

    <div class="footer">
      <%= link_to image_tag("twitter.png"), "https://twitter.com/haurilmnisfari"  %>
      <%= link_to image_tag("facebook.png"), "https://www.facebook.com/haurilmaulida.nisfari"  %>
      <%= link_to image_tag("instagram.png"), "https://www.instagram.com/haurilmnisfari"  %>
      <%= link_to image_tag("linkedin.png"), "https://www.linkedin.com/in/hauril-maulida-nisfari-7b8a6891/"  %>
    </div>

  </body>
</html>