config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  resources :categories
  resources :accounts, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'accounts#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as:'logout'
  resources :stories

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :load_popular_posts, except: [:destroy]
  before_action :load_categories, except: [:destroy]
  http_basic_authenticate_with name: Rails.application.credentials.http_basic_auth[:username], password: Rails.application.credentials.http_basic_auth[:password], only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(resource_params)

    if @user.save
      flash[:notice] = "Account has been created"
      redirect_to login_path
    else
      render "new"
    end
  end

  def resource_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation)
  end
end

app/views/accounts/new.html.erb
<%= form_for @user, url: accounts_path  do |f| %>
  <div>
    <%= f.label :name %>
  </div>
  <div>
    <%= f.text_field :name %>
  </div>
  <% if @user.errors[:name].present? %>
    <span class="red-text small-text">
      <%= 'Name ' + @user.errors[:name].join(", ") %>
    </span>
  <% end %>

  <div>
    <%= f.label :username %>
  </div>
  <div>
    <%= f.text_field :username %>
  </div>
  <% if @user.errors[:username].present? %>
    <span class="red-text small-text">
      <%= 'Username ' + @user.errors[:username].join(", ") %>
    </span>
  <% end %>

  <div>
    <%= f.label :password %>
  </div>
  <div>
    <%= f.password_field :password %>
  </div>
  <% if @user.errors[:password].present? %>
    <span class="red-text small-text">
      <%= 'Password ' + @user.errors[:password].join(", ") %>
    </span>
  <% end %>

  <div>
    <%= f.label :password_confirmation %>
  </div>
  <div>
    <%= f.password_field :password_confirmation %>
  </div>
  <%if @user.errors[:password_confirmation].present? %>
    <span class="red-text small-text">
      <%= 'Password Confirmation ' + @user.errors[:password_confirmation].join(", ") %>
    </span>
  <% end %>

  <div>
    <%= f.submit "Register", notice: 'Berhasil registrasi !' %>
  </div>

<% end %>